dist: xenial
language: bash

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y texlive-full

script:
  - echo "Building PDF for CV"
  - cd src
  - xelatex cv.tex \cv
  - ls

after_script:
  - echo "[TODO] After build script"

after_success:
  - echo "[TODO] After build script success"
