dist: xenial
language: bash

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y texlive-full

script:
  - echo "Building PDF for CV"
  - cd src
  - mkdir _build
  - xelatex cv.tex \cv
  - ls -l
  - if [ ! -f "cv.pdf" ]; then echo "CV PDF not found"; exit 1; fi
  - cp cv.pdf _build/Adisakshya_Chauhan_CV.pdf 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: src/_build
  on:
    branch: master
